import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button, buttonVariants } from "@/components/ui/button";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "For Sujana",
  description: "Generated by create next app",
  icons: {
    icon: "logo.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="absolute left-0 top-0 z-50 w-full px-8 py-6">
          <div className="mx-auto flex w-full max-w-5xl flex-col items-center justify-center gap-2">
            <Link
              className="text-center text-[300%] uppercase tracking-[0.2em] text-foreground"
              href="/"
            >
              For Sujana:
            </Link>
            <div className="app-subtitle">
              
            </div>
          </div>
        </header>
        {children}
        <footer className="app-footer">Developed by Parrot & Chatgpt (I did 99% of the work though promis fr) </footer>
      </body>
    </html>
  );
}
