import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button, buttonVariants } from "@/components/ui/button";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "For Sujana",
  description: "Generated by create next app",
  icons: {
    icon: "logo.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="absolute left-0 top-0 z-50 w-full px-8 py-6">
          <Link href="/" className="app-home-icon-button" aria-label="Home">
            <span className="app-home-icon" aria-hidden="true"></span>
          </Link>
          <div className="mx-auto flex w-full max-w-5xl flex-col items-center justify-center gap-2">
            <Link
              className="text-center text-[300%] uppercase tracking-[0.2em] text-foreground"
              href="/"
            >
              <span className="inline-flex items-center gap-3">
                For Sujana:
                <img src="heart.png" alt="" className="app-heart-icon" />
              </span>
            </Link>
            <div className="app-subtitle">A website dedicated to sujana kabir nova</div>
          </div>
        </header>
        {children}
        <footer className="app-footer">Developed and Designed By: parrot </footer>
      </body>
    </html>
  );
}
